project:
  type: website

website:
  title: "Tianqi Zhang"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: CV
        href: cv.pdf
      - text: Study Notes
        file: study-notes/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



